before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - tunl
    image_templates:
    - "tunl/tunl:latest"
    - "tunl/tunl:{{ .Tag }}"
    - "tunl/tunl:v{{ .Major }}.{{ .Minor }}"
    - "docker.pkg.github.com/pjvds/tunl/tunl:latest"
    - "docker.pkg.github.com/pjvds/tunl/tunl:{{ .Tag }}"
    - "docker.pkg.github.com/pjvds/tunl/tunl:v{{ .Major }}.{{ .Minor }}"
    extra_files:

snapcrafts:
  -
    # ID of the snapcraft config, must be unique.
    # Defaults to "default".
    id: tunl
    summary: Expose your localhost to the public via an secure tunnel
    description: With Tunl you can expose services on your localhost to the public via a fast and secure tunnel.
    grade: devel
    confinement: strict
    license: MIT
    base: bare

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
