before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - tunl
    image_templates:
    - "docker.pkg.github.com/pjvds/tunl:latest"
    - "docker.pkg.github.com/pjvds/tunl:{{ .Tag }}"
    - "docker.pkg.github.com/pjvds/tunl:v{{ .Major }}.{{ .Minor }}"
    extra_files:

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
