name: build
on:
  push:
    branches:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Get go 1.16beta1
        run: |
          go get golang.org/dl/go1.16beta1
          go1.16beta1 download
          
      - 
        name: Update APT
        run: sudo apt-get -yq update
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist
